services:
  api:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
  client:
    build:
      context: './Client'
      dockerfile: Dockerfile
    ports:
      - "3001:3000"